---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: 34.79.12.33
      ansible_port: 22
      ansible_ssh_user: rg
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    deployment1:
      ansible_host: 34.79.12.33
      ansible_port: 22
      ansible_ssh_user: rg
  vars:
    ansible_python_interpreter: /usr/bin/python3
